# Generated by Django 2.0 on 2018-01-08 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsessionmember',
            name='chat_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='chat.ChatSession'),
        ),
        migrations.AlterField(
            model_name='chatsessionmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
