# Generated by Django 2.0 on 2018-01-08 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20180108_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsessionmessage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatsessionmessage',
            name='chat_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='chat.ChatSession'),
        ),
    ]
