# Generated by Django 2.0 on 2018-01-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180108_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='url',
            new_name='uri',
        ),
    ]
